// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IBioFields {
    /** Section Label */
    sectionLabel?: string | undefined;

    /** Bio */
    bio?: Document | undefined;
}

export interface IBio extends Entry<IBioFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'bio';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IHeaderFields {
    /** Logo */
    logo?: Asset | undefined;

    /** Github Link */
    githubLink?: string | undefined;

    /** Tag Line */
    tagLine?: string | undefined;

    /** Tag Line Endings */
    tagLineEndings?: Record<string, any> | undefined;
}

export interface IHeader extends Entry<IHeaderFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'header';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IProjectPostFields {
    /** Project Title */
    projectTitle: string;

    /** projectImage */
    projectImage?: Asset | undefined;

    /** Project Link */
    projectLink?: string | undefined;

    /** Github Repo */
    githubRepo?: string | undefined;

    /** tags */
    tags?: IProjectTag[] | undefined;

    /** Project Post */
    projectPost?: Document | undefined;

    /** Project Description */
    projectDescription?: Document | undefined;
}

/** Model for a dev project */

export interface IProjectPost extends Entry<IProjectPostFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'projectPost';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IProjectSectionFields {
    /** Project Section Title */
    projectSectionTitle?: string | undefined;

    /** Project Posts */
    projectPosts?: IProjectPost[] | undefined;
}

export interface IProjectSection extends Entry<IProjectSectionFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'projectSection';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IProjectTagFields {
    /** Tag Title */
    tagTitle?: string | undefined;

    /** tagIcon */
    tagIcon?: Asset | undefined;
}

/** A tag, used either on project or resume posts */

export interface IProjectTag extends Entry<IProjectTagFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'projectTag';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IResumePostFields {
    /** Company Name */
    companyName?: string | undefined;

    /** Job Title */
    jobTitle?: string | undefined;

    /** Job Start Date */
    jobStartDate?: string | undefined;

    /** Job Dates */
    jobDates?: string | undefined;

    /** Job Dates 2 */
    jobDates2?: string | undefined;

    /** Job Description */
    jobDescription?: Document | undefined;

    /** tags */
    tags?: IProjectTag[] | undefined;
}

export interface IResumePost extends Entry<IResumePostFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'resumePost';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export interface IResumeSectionFields {
    /** Resume Section Title */
    resumeSectionTitle?: string | undefined;

    /** Job Posts */
    jobPosts?: IResumePost[] | undefined;
}

export interface IResumeSection extends Entry<IResumeSectionFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'resumeSection';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export type CONTENT_TYPE =
    | 'bio'
    | 'header'
    | 'projectPost'
    | 'projectSection'
    | 'projectTag'
    | 'resumePost'
    | 'resumeSection';

export type IEntry =
    | IBio
    | IHeader
    | IProjectPost
    | IProjectSection
    | IProjectTag
    | IResumePost
    | IResumeSection;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
