import { Photo } from '../../../models/image.model';

export const TripsConfig = [
    {
        name: 'Yellowstone/Grand Teton',
        shortDescription: '',
        location: 'Idaho & Wyoming, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'August 2023',
        coverImageUrl:
            'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/emerald-pond.webp',
        // coverImageUrl: 'https://clemann.app/2023/wyoming/lake_of_crags1.jpeg',
        path: 'travels/2023-08-Wyoming',
    },
    {
        name: 'Smokey Mountains',
        shortDescription: '',
        location: 'Gatlinburg TN, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'May 2023',
        coverImageUrl: 'https://clemann.app/2023/tennessee/smokey.jpeg',
        path: 'travels/2023-05-Smokey',
    },
    {
        name: 'F1 Miami GrandPrix',
        shortDescription: '',
        location: 'Miami FL, USA',
        tags: ['🏁 Event'],
        dates: 'May 2023',
        coverImageUrl: 'https://clemann.app/2023/miami-f1/f1-cover.jpeg',
        path: 'travels/2023-05-F1',
    },
    {
        name: 'Vermont',
        shortDescription: '',
        location: 'Okemo VT, USA',
        tags: ['🏂 Snowboarding'],
        dates: 'February 2023',
        coverImageUrl: 'https://clemann.app/2023/vermont/vermont-cover.jpeg',
        path: 'travels/2023-02-Vermont',
    },
    {
        name: 'Whistler',
        shortDescription: '',
        location: 'Whistler BC, Canada',
        tags: ['🏂 Snowboarding'],
        dates: 'January 2023',
        coverImageUrl: 'https://clemann.app/2023/bc/whistler-cover.jpeg',
        path: 'travels/2023-01-Whistler',
    },
    {
        name: 'Switzerland',
        shortDescription: '',
        location: 'Zermatt/Zurich, Switzerland',
        tags: ['🏂 Snowboarding', '🏔️ Hiking'],
        dates: 'December 2022',
        coverImageUrl:
            'https://clemann.app/2022/switzerland/zermatt-cover.jpeg',
        path: 'travels/2022-12-Switzerland',
    },
    {
        name: 'Aspen',
        shortDescription: '',
        location: 'Aspen CO, USA',
        tags: ['🏂 Snowboarding'],
        dates: 'January 2022',
        coverImageUrl: 'https://clemann.app/2022/aspen/aspen-cover.jpeg',
        path: 'travels/2022-01-Aspen',
    },
    {
        name: 'Yosemite/Napa/SF',
        shortDescription: '',
        location: 'California, USA',
        tags: ['🏞️ National Park'],
        dates: 'August 2021',
        coverImageUrl:
            'https://clemann.app/2022/california/yosemite-cover.jpeg',
        path: 'travels/2021-08-California',
    },
    {
        name: 'Rocky Mountain National Park',
        shortDescription: '',
        location: 'Colorado, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'August 2020',
        coverImageUrl: 'https://clemann.app/2020/colorado/rocky-cover.jpeg',
        path: 'travels/2020-08-Colorado',
    },
    {
        name: 'Europe',
        shortDescription: '',
        location: 'France/Switzerland/Italy',
        tags: ['🌎 Sightseeing'],
        dates: 'June 2019',
        coverImageUrl: 'https://clemann.app/2019/europe/wengen-cover.jpeg',
        path: 'travels/2019-06-Europe',
    },
];

export const ImagesConfig = {
    '2023/wyoming/yellowstone': {
        panos: [],
        images: [
            {
                id: 'dnr-sign',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/dnr-sign.webp',
            },
            {
                id: 'fam-sign',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/fam-sign.webp',
            },
            {
                id: 'old-faithful-rachel',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/old-faithful-rachel.webp',
            },
            {
                id: 'plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/plains.webp',
            },
            {
                id: 'river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river.webp',
            },
            {
                id: 'river2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river2.webp',
            },
            {
                id: 'river3',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river3.webp',
            },
            {
                id: 'snake',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/snake.webp',
            },
            {
                id: 'yellowstone-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/yellowstone-lake.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/washburn': {
        panos: [],
        images: [
            {
                id: 'canyon-eidge-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-eidge-view.webp',
            },
            {
                id: 'canyon-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-view.webp',
            },
            {
                id: 'canyon-zoom',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-zoom.webp',
            },
            {
                id: 'mountain-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/mountain-view.webp',
            },
            {
                id: 'plains-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/plains-view.webp',
            },
            {
                id: 'rnr-climb',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-climb.webp',
            },
            {
                id: 'rnr-ridge-walk-2',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-ridge-walk-2.webp',
            },
            {
                id: 'rnr-ridge-walk',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-ridge-walk.webp',
            },
            {
                id: 'summit-dylan-wide',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/summit-dylan-wide.webp',
            },
            {
                id: 'summit-dylan',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/summit-dylan.webp',
            },
            {
                id: 'vista',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/vista.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/geysers': {
        panos: [],
        images: [
            {
                id: 'artists-paintpots',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/artists-paintpots.webp',
            },
            {
                id: 'basin-geyser',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/basin-geyser.webp',
            },
            {
                id: 'basin',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/basin.webp',
            },
            {
                id: 'mammoth',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/mammoth.webp',
            },
            {
                id: 'midway-colors',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-colors.webp',
            },
            {
                id: 'midway-flats-reflect',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-flats-reflect.webp',
            },
            {
                id: 'midway-flats',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-flats.webp',
            },
            {
                id: 'midway-pool',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-pool.webp',
            },
            {
                id: 'salt-flats',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/salt-flats.webp',
            },
            {
                id: 'saphire-pool',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/saphire-pool.webp',
            },
            {
                id: 'saphire-pool2',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/saphire-pool2.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/firehole': {
        panos: [],
        images: [
            {
                id: 'firehole-boys',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-boys.webp',
            },
            {
                id: 'firehole-dnr',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-dnr.webp',
            },
            {
                id: 'firehole-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-falls.webp',
            },
            {
                id: 'firehole-rachel',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-rachel.webp',
            },
            {
                id: 'firehole-rock-collect',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-rock-collect.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/bison': {
        panos: [],
        images: [
            {
                id: 'bison-close-up',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-close-up.webp',
            },
            {
                id: 'bison-crowd',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-crowd.webp',
            },
            {
                id: 'bison-plains-2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-plains-2.webp',
            },
            {
                id: 'bison-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-plains.webp',
            },
            {
                id: 'bison-side',
                width: 1501,
                height: 844,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-side.webp',
            },
            {
                id: 'bison-sunset',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-sunset.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/artist-point': {
        panos: [],
        images: [
            {
                id: 'canyon-wall',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/canyon-wall.webp',
            },
            {
                id: 'canyon-wall2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/canyon-wall2.webp',
            },
            {
                id: 'dad-falls',
                width: 1564,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/dad-falls.webp',
            },
            {
                id: 'dnr-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/dnr-falls.webp',
            },
            {
                id: 'falls-and-river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls-and-river.webp',
            },
            {
                id: 'falls-close-up',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls-close-up.webp',
            },
            {
                id: 'falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls.webp',
            },
            {
                id: 'fam',
                width: 744,
                height: 1249,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/fam.webp',
            },
            {
                id: 'lower-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/lower-falls.webp',
            },
            {
                id: 'tnr-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/tnr-plains.webp',
            },
            {
                id: 'upper-falls',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/upper-falls.webp',
            },
        ],
    },
    '2023/wyoming/teton': {
        panos: [],
        images: [
            {
                id: '000-rachel-binocs',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/000-rachel-binocs.webp',
            },
            {
                id: '001-toten-pass-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/001-toten-pass-sign.webp',
            },
            {
                id: '002-taggart-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/002-taggart-lake.webp',
            },
            {
                id: '003-bike-trail-mountains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/003-bike-trail-mountains.webp',
            },
            {
                id: '004-jackson-hole-summit2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/004-jackson-hole-summit2.webp',
            },
            {
                id: '005-jackson-hole-summit',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/005-jackson-hole-summit.webp',
            },
            {
                id: '006-jagged-view',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/006-jagged-view.webp',
            },
            {
                id: '007-jagged-plains-view',
                width: 2016,
                height: 1033,
                src: 'https://clemann.app/2023/wyoming/teton/007-jagged-plains-view.webp',
            },
            {
                id: '008-glacier-point-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/008-glacier-point-plains.webp',
            },
            {
                id: '009-glacier-point',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/009-glacier-point.webp',
            },
            {
                id: '010-glacier-point-plains2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/010-glacier-point-plains2.webp',
            },
            {
                id: '011-jenny-lake-2',
                width: 1909,
                height: 1432,
                src: 'https://clemann.app/2023/wyoming/teton/011-jenny-lake-2.webp',
            },
            {
                id: '012-jenny-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/012-jenny-lake.webp',
            },
            {
                id: '013-jackson-lake-wide',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/013-jackson-lake-wide.webp',
            },
            {
                id: '014-jackson-lake',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/014-jackson-lake.webp',
            },
            {
                id: '015-teton-kayak2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/015-teton-kayak2.webp',
            },
            {
                id: '016-teton-kayak-beer',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/016-teton-kayak-beer.webp',
            },
            {
                id: '017-tetons-kayak',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/017-tetons-kayak.webp',
            },
            {
                id: '018-bear-country-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/018-bear-country-sign.webp',
            },
            {
                id: '019-forest-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/019-forest-walk.webp',
            },
            {
                id: '020-hidden-falls',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/020-hidden-falls.webp',
            },
            {
                id: '021-river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/021-river.webp',
            },
            {
                id: '022-',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/022-.webp',
            },
            {
                id: '023-teton-sunset',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/023-teton-sunset.webp',
            },
        ],
    },
    '2023/wyoming/teton/table-mountain': {
        panos: [
            {
                id: 'pano-001-table-down-vista-pano',
                width: 8152,
                height: 1892,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-001-table-down-vista-pano.webp',
            },
            {
                id: 'pano-002-pano-vista',
                width: 7650,
                height: 1893,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-002-pano-vista.webp',
            },
            {
                id: 'pano-003-rachel-sit-pano',
                width: 3369,
                height: 1927,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-003-rachel-sit-pano.webp',
            },
            {
                id: 'pano-004-grand-teton-pano',
                width: 8130,
                height: 1910,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-004-grand-teton-pano.webp',
            },
            {
                id: 'pano-005-table-tip-pano',
                width: 6391,
                height: 1927,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-005-table-tip-pano.webp',
            },
            {
                id: 'pano-006-table-mountain-full-pano',
                width: 7973,
                height: 1894,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-006-table-mountain-full-pano.webp',
            },
        ],
        images: [
            {
                id: '001-very-steep-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/001-very-steep-sign.webp',
            },
            {
                id: '002-canyon-wall-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/002-canyon-wall-view.webp',
            },
            {
                id: '003-mountain-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/003-mountain-plains.webp',
            },
            {
                id: '004-mountain-plains2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/004-mountain-plains2.webp',
            },
            {
                id: '005',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/005.webp',
            },
            {
                id: '006-mountain-wall-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/006-mountain-wall-view.webp',
            },
            {
                id: '007-rachel-sit-vista',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/007-rachel-sit-vista.webp',
            },
            {
                id: '008-canyon-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/008-canyon-selfie.webp',
            },
            {
                id: '010-selfie-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/010-selfie-plains.webp',
            },
            {
                id: '011-table-up-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/011-table-up-view.webp',
            },
            {
                id: '012-rockfall-canyon',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/012-rockfall-canyon.webp',
            },
            {
                id: '013-table-up-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/013-table-up-selfie.webp',
            },
            {
                id: '014-table-climb',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/014-table-climb.webp',
            },
            {
                id: '015-grand-teton',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/015-grand-teton.webp',
            },
            {
                id: '016-dnr-teets',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/016-dnr-teets.webp',
            },
            {
                id: '017-teton-dylan-ridge',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/017-teton-dylan-ridge.webp',
            },
            {
                id: '018-dylan-table-top-arms',
                width: 1937,
                height: 1329,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/018-dylan-table-top-arms.webp',
            },
            {
                id: '019-dnr-teton-tip',
                width: 2015,
                height: 1389,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/019-dnr-teton-tip.webp',
            },
            {
                id: '020-rachel-overlook',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/020-rachel-overlook.webp',
            },
            {
                id: '021-deer',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/021-deer.webp',
            },
        ],
    },
    '2023/wyoming/teton/mount-glory': {
        panos: [
            {
                id: 'pano-001-mount-glory',
                width: 7895,
                height: 1894,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/pano-001-mount-glory.webp',
            },
        ],
        images: [
            {
                id: '001-mount-glory-hike',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/001-mount-glory-hike.webp',
            },
            {
                id: '002-hike-down',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/002-hike-down.webp',
            },
            {
                id: '003-bowl',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/003-bowl.webp',
            },
            {
                id: '004-bowl-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/004-bowl-view.webp',
            },
            {
                id: '005-summit-rachel',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/005-summit-rachel.webp',
            },
            {
                id: '006-bowl-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/006-bowl-walk.webp',
            },
            {
                id: '007-bowl-walk2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/007-bowl-walk2.webp',
            },
            {
                id: '008-ridge-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/008-ridge-walk.webp',
            },
            {
                id: '009-ridge-walk-2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/009-ridge-walk-2.webp',
            },
            {
                id: '010-rock-picking',
                width: 1134,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/010-rock-picking.webp',
            },
            {
                id: '011-ski-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/011-ski-lake.webp',
            },
        ],
    },
    '2023/wyoming/teton/lake-of-the-crags': {
        panos: [],
        images: [
            {
                id: '001-jenny-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/001-jenny-lake.webp',
            },
            {
                id: '002-climb-up0view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/002-climb-up0view.webp',
            },
            {
                id: '003-climb-up-view-dnr',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/003-climb-up-view-dnr.webp',
            },
            {
                id: '004-emerald-pond',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/004-emerald-pond.webp',
            },
            {
                id: '005-lake-of-the-crags',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/005-lake-of-the-crags.webp',
            },
            {
                id: '006-lake-of-the-crags-rachel-hands-up',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/006-lake-of-the-crags-rachel-hands-up.webp',
            },
            {
                id: '007-lake-of-the-crags-dnr',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/007-lake-of-the-crags-dnr.webp',
            },
            {
                id: '008-lake-of-the-crags-selfie',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/008-lake-of-the-crags-selfie.webp',
            },
            {
                id: '009-lake-of-the-crags-nap',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/009-lake-of-the-crags-nap.webp',
            },
            {
                id: '010-lake-of-the-crags-boys',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/010-lake-of-the-crags-boys.webp',
            },
        ],
    },
    '2023/wyoming/teton/cascade-creek': {
        panos: [],
        images: [
            {
                id: '001-creek-vista',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/001-creek-vista.webp',
            },
            {
                id: '002-creek',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/002-creek.webp',
            },
            {
                id: '003-dnr-canyon-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/003-dnr-canyon-view.webp',
            },
            {
                id: '004-valley-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/004-valley-view.webp',
            },
            {
                id: '005-valley-view2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/005-valley-view2.webp',
            },
            {
                id: '006-valley-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/006-valley-walk.webp',
            },
            {
                id: '007-glacier',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/007-glacier.webp',
            },
            {
                id: '008-glacier2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/008-glacier2.webp',
            },
            {
                id: '009-endor-view',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/009-endor-view.webp',
            },
            {
                id: '010-endor-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/010-endor-walk.webp',
            },
        ],
    },
    '2023/wyoming/random': {
        panos: [],
        images: [
            {
                id: 'battle-of-pierres-hole',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/battle-of-pierres-hole.webp',
            },
            {
                id: 'earned-it',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/earned-it.webp',
            },
            {
                id: 'kampai-drinks',
                width: 1316,
                height: 1755,
                src: 'https://clemann.app/2023/wyoming/random/kampai-drinks.webp',
            },
            {
                id: 'kampai-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/kampai-selfie.webp',
            },
            {
                id: 'kampai-sushi',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/kampai-sushi.webp',
            },
            {
                id: 'old-faithful-ipa',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/old-faithful-ipa.webp',
            },
            {
                id: 'ron-smokey',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/ron-smokey.webp',
            },
            {
                id: 'stars',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/stars.webp',
            },
            {
                id: 'tips-up',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/tips-up.webp',
            },
            {
                id: 'yellowstone-whiskey',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/yellowstone-whiskey.webp',
            },
        ],
    },
};
