import { Photo } from '../../../models/image.model';

export const TripsConfig = [
    {
        name: 'Yellowstone/Grand Teton',
        shortDescription: '',
        location: 'Idaho & Wyoming, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'August 2023',
        coverImageUrl:
            'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/emerald-pond.webp',
        // coverImageUrl: 'https://clemann.app/2023/wyoming/lake_of_crags1.jpeg',
        path: 'travels/2023-08-Wyoming',
    },
    {
        name: 'Smokey Mountains',
        shortDescription: '',
        location: 'Gatlinburg TN, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'May 2023',
        coverImageUrl: 'https://clemann.app/2023/tennessee/smokey.jpeg',
        path: 'travels/2023-05-Smokey',
    },
    {
        name: 'F1 Miami GrandPrix',
        shortDescription: '',
        location: 'Miami FL, USA',
        tags: ['🏁 Event'],
        dates: 'May 2023',
        coverImageUrl: 'https://clemann.app/2023/miami-f1/f1-cover.jpeg',
        path: 'travels/2023-05-F1',
    },
    {
        name: 'Vermont',
        shortDescription: '',
        location: 'Okemo VT, USA',
        tags: ['🏂 Snowboarding'],
        dates: 'February 2023',
        coverImageUrl: 'https://clemann.app/2023/vermont/vermont-cover.jpeg',
        path: 'travels/2023-02-Vermont',
    },
    {
        name: 'Whistler',
        shortDescription: '',
        location: 'Whistler BC, Canada',
        tags: ['🏂 Snowboarding'],
        dates: 'January 2023',
        coverImageUrl: 'https://clemann.app/2023/bc/whistler-cover.jpeg',
        path: 'travels/2023-01-Whistler',
    },
    {
        name: 'Switzerland',
        shortDescription: '',
        location: 'Zermatt/Zurich, Switzerland',
        tags: ['🏂 Snowboarding', '🏔️ Hiking'],
        dates: 'December 2022',
        coverImageUrl:
            'https://clemann.app/2022/switzerland/zermatt-cover.jpeg',
        path: 'travels/2022-12-Switzerland',
    },
    {
        name: 'Aspen',
        shortDescription: '',
        location: 'Aspen CO, USA',
        tags: ['🏂 Snowboarding'],
        dates: 'January 2022',
        coverImageUrl: 'https://clemann.app/2022/aspen/aspen-cover.jpeg',
        path: 'travels/2022-01-Aspen',
    },
    {
        name: 'Yosemite/Napa/SF',
        shortDescription: '',
        location: 'California, USA',
        tags: ['🏞️ National Park'],
        dates: 'August 2021',
        coverImageUrl:
            'https://clemann.app/2022/california/yosemite-cover.jpeg',
        path: 'travels/2021-08-California',
    },
    {
        name: 'Rocky Mountain National Park',
        shortDescription: '',
        location: 'Colorado, USA',
        tags: ['🏞️ National Park', '⛰️ Hiking'],
        dates: 'August 2020',
        coverImageUrl: 'https://clemann.app/2020/colorado/rocky-cover.jpeg',
        path: 'travels/2020-08-Colorado',
    },
    {
        name: 'Europe',
        shortDescription: '',
        location: 'France/Switzerland/Italy',
        tags: ['🌎 Sightseeing'],
        dates: 'June 2019',
        coverImageUrl: 'https://clemann.app/2019/europe/wengen-cover.jpeg',
        path: 'travels/2019-06-Europe',
    },
];

export const ImagesConfig = {
    '2023/wyoming/yellowstone': {
        panos: [],
        images: [
            {
                id: 'dnr-sign',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/dnr-sign.webp',
            },
            {
                id: 'fam-sign',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/fam-sign.webp',
            },
            {
                id: 'old-faithful-rachel',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/old-faithful-rachel.webp',
            },
            {
                id: 'plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/plains.webp',
            },
            {
                id: 'river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river.webp',
            },
            {
                id: 'river2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river2.webp',
            },
            {
                id: 'river3',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/river3.webp',
            },
            {
                id: 'snake',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/snake.webp',
            },
            {
                id: 'yellowstone-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/yellowstone-lake.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/washburn': {
        panos: [],
        images: [
            {
                id: 'canyon-eidge-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-eidge-view.webp',
            },
            {
                id: 'canyon-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-view.webp',
            },
            {
                id: 'canyon-zoom',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/canyon-zoom.webp',
            },
            {
                id: 'mountain-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/mountain-view.webp',
            },
            {
                id: 'plains-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/plains-view.webp',
            },
            {
                id: 'rnr-climb',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-climb.webp',
            },
            {
                id: 'rnr-ridge-walk-2',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-ridge-walk-2.webp',
            },
            {
                id: 'rnr-ridge-walk',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/rnr-ridge-walk.webp',
            },
            {
                id: 'summit-dylan-wide',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/summit-dylan-wide.webp',
            },
            {
                id: 'summit-dylan',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/summit-dylan.webp',
            },
            {
                id: 'vista',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/washburn/vista.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/geysers': {
        panos: [],
        images: [
            {
                id: 'artists-paintpots',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/artists-paintpots.webp',
            },
            {
                id: 'basin-geyser',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/basin-geyser.webp',
            },
            {
                id: 'basin',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/basin.webp',
            },
            {
                id: 'mammoth',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/mammoth.webp',
            },
            {
                id: 'midway-colors',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-colors.webp',
            },
            {
                id: 'midway-flats-reflect',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-flats-reflect.webp',
            },
            {
                id: 'midway-flats',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-flats.webp',
            },
            {
                id: 'midway-pool',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/midway-pool.webp',
            },
            {
                id: 'salt-flats',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/salt-flats.webp',
            },
            {
                id: 'saphire-pool',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/saphire-pool.webp',
            },
            {
                id: 'saphire-pool2',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/geysers/saphire-pool2.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/firehole': {
        panos: [],
        images: [
            {
                id: 'firehole-boys',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-boys.webp',
            },
            {
                id: 'firehole-dnr',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-dnr.webp',
            },
            {
                id: 'firehole-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-falls.webp',
            },
            {
                id: 'firehole-rachel',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-rachel.webp',
            },
            {
                id: 'firehole-rock-collect',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/firehole/firehole-rock-collect.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/bison': {
        panos: [],
        images: [
            {
                id: 'bison-close-up',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-close-up.webp',
            },
            {
                id: 'bison-crowd',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-crowd.webp',
            },
            {
                id: 'bison-plains-2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-plains-2.webp',
            },
            {
                id: 'bison-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-plains.webp',
            },
            {
                id: 'bison-side',
                width: 1501,
                height: 844,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-side.webp',
            },
            {
                id: 'bison-sunset',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/bison/bison-sunset.webp',
            },
        ],
    },
    '2023/wyoming/yellowstone/artist-point': {
        panos: [],
        images: [
            {
                id: 'canyon-wall',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/canyon-wall.webp',
            },
            {
                id: 'canyon-wall2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/canyon-wall2.webp',
            },
            {
                id: 'dad-falls',
                width: 1564,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/dad-falls.webp',
            },
            {
                id: 'dnr-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/dnr-falls.webp',
            },
            {
                id: 'falls-and-river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls-and-river.webp',
            },
            {
                id: 'falls-close-up',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls-close-up.webp',
            },
            {
                id: 'falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/falls.webp',
            },
            {
                id: 'fam',
                width: 744,
                height: 1249,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/fam.webp',
            },
            {
                id: 'lower-falls',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/lower-falls.webp',
            },
            {
                id: 'tnr-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/tnr-plains.webp',
            },
            {
                id: 'upper-falls',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/yellowstone/artist-point/upper-falls.webp',
            },
        ],
    },
    '2023/wyoming/teton': {
        panos: [],
        images: [
            {
                id: 'bear-country-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/bear-country-sign.webp',
            },
            {
                id: 'bike-trail-mountains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/bike-trail-mountains.webp',
            },
            {
                id: 'forest-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/forest-walk.webp',
            },
            {
                id: 'glacier-point-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/glacier-point-plains.webp',
            },
            {
                id: 'glacier-point-plains2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/glacier-point-plains2.webp',
            },
            {
                id: 'glacier-point',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/glacier-point.webp',
            },
            {
                id: 'hidden-falls',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/hidden-falls.webp',
            },
            {
                id: 'jackson-hole-summit',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/jackson-hole-summit.webp',
            },
            {
                id: 'jackson-hole-summit2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/jackson-hole-summit2.webp',
            },
            {
                id: 'jackson-lake-wide',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/jackson-lake-wide.webp',
            },
            {
                id: 'jackson-lake',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/jackson-lake.webp',
            },
            {
                id: 'jagged-plains-view',
                width: 2016,
                height: 1033,
                src: 'https://clemann.app/2023/wyoming/teton/jagged-plains-view.webp',
            },
            {
                id: 'jagged-view',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/jagged-view.webp',
            },
            {
                id: 'jenny-lake-2',
                width: 1909,
                height: 1432,
                src: 'https://clemann.app/2023/wyoming/teton/jenny-lake-2.webp',
            },
            {
                id: 'jenny-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/jenny-lake.webp',
            },
            {
                id: 'moose-ponds',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/moose-ponds.webp',
            },
            {
                id: 'rachel-binocs',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/rachel-binocs.webp',
            },
            {
                id: 'river',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/river.webp',
            },
            {
                id: 'taggart-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/taggart-lake.webp',
            },
            {
                id: 'teton-kayak-beer',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/teton-kayak-beer.webp',
            },
            {
                id: 'teton-kayak2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/teton-kayak2.webp',
            },
            {
                id: 'teton-sunset',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/teton-sunset.webp',
            },
            {
                id: 'tetons-kayak',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/tetons-kayak.webp',
            },
            {
                id: 'toten-pass-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/toten-pass-sign.webp',
            },
        ],
    },
    '2023/wyoming/teton/table-mountain': {
        panos: [
            {
                id: 'grand-teton-pano',
                width: 8130,
                height: 1910,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/grand-teton-pano.webp',
            },
            {
                id: 'pano-vista',
                width: 7650,
                height: 1893,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/pano-vista.webp',
            },
            {
                id: 'rachel-sit-pano',
                width: 3369,
                height: 1927,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/rachel-sit-pano.webp',
            },
            {
                id: 'table-down-vista-pano',
                width: 8152,
                height: 1892,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-down-vista-pano.webp',
            },
            {
                id: 'table-mountain-full-pano',
                width: 7973,
                height: 1894,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-mountain-full-pano.webp',
            },
            {
                id: 'table-tip-pano',
                width: 6391,
                height: 1927,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-tip-pano.webp',
            },
        ],
        images: [
            {
                id: 'canyon-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/canyon-selfie.webp',
            },
            {
                id: 'canyon-wall-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/canyon-wall-view.webp',
            },
            {
                id: 'deer',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/deer.webp',
            },
            {
                id: 'dnr-teets',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/dnr-teets.webp',
            },
            {
                id: 'dnr-teton-tip',
                width: 2015,
                height: 1389,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/dnr-teton-tip.webp',
            },
            {
                id: 'dylan-table-top-arms',
                width: 1937,
                height: 1329,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/dylan-table-top-arms.webp',
            },
            {
                id: 'grand-teton',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/grand-teton.webp',
            },
            {
                id: 'mountain-plains',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/mountain-plains.webp',
            },
            {
                id: 'mountain-plains2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/mountain-plains2.webp',
            },
            {
                id: 'mountain-plains3',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/mountain-plains3.webp',
            },
            {
                id: 'mountain-wall-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/mountain-wall-view.webp',
            },
            {
                id: 'rachel-overlook',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/rachel-overlook.webp',
            },
            {
                id: 'rachel-sit-vista',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/rachel-sit-vista.webp',
            },
            {
                id: 'rockfall-canyon',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/rockfall-canyon.webp',
            },
            {
                id: 'table-climb',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-climb.webp',
            },
            {
                id: 'table-up-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-up-selfie.webp',
            },
            {
                id: 'table-up-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/table-up-view.webp',
            },
            {
                id: 'teton-dylan-ridge',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/teton-dylan-ridge.webp',
            },
            {
                id: 'very-steep-sign',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/very-steep-sign.webp',
            },
            {
                id: 'vista-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/table-mountain/vista-selfie.webp',
            },
        ],
    },
    '2023/wyoming/teton/mount-glory': {
        panos: [
            {
                id: 'pano',
                width: 7895,
                height: 1894,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/pano.webp',
            },
        ],
        images: [
            {
                id: 'bowl-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/bowl-view.webp',
            },
            {
                id: 'bowl-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/bowl-walk.webp',
            },
            {
                id: 'bowl-walk2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/bowl-walk2.webp',
            },
            {
                id: 'bowl',
                width: 2016,
                height: 1134,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/bowl.webp',
            },
            {
                id: 'hike-down',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/hike-down.webp',
            },
            {
                id: 'mount-glory-hike',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/mount-glory-hike.webp',
            },
            {
                id: 'ridge-walk-2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/ridge-walk-2.webp',
            },
            {
                id: 'ridge-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/ridge-walk.webp',
            },
            {
                id: 'rock-picking',
                width: 1134,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/rock-picking.webp',
            },
            {
                id: 'ski-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/ski-lake.webp',
            },
            {
                id: 'summit-rachel',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/mount-glory/summit-rachel.webp',
            },
        ],
    },
    '2023/wyoming/teton/lake-of-the-crags': {
        panos: [],
        images: [
            {
                id: 'emerald-pond',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/emerald-pond.webp',
            },
            {
                id: 'jenny-lake',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/jenny-lake.webp',
            },
            {
                id: 'lake-of-the-crags-boys',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags-boys.webp',
            },
            {
                id: 'lake-of-the-crags-dnr',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags-dnr.webp',
            },
            {
                id: 'lake-of-the-crags-nap',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags-nap.webp',
            },
            {
                id: 'lake-of-the-crags-rachel-hands-up',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags-rachel-hands-up.webp',
            },
            {
                id: 'lake-of-the-crags-selfie',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags-selfie.webp',
            },
            {
                id: 'lake-of-the-crags',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/lake-of-the-crags/lake-of-the-crags.webp',
            },
        ],
    },
    '2023/wyoming/teton/cascade-creek': {
        panos: [],
        images: [
            {
                id: 'creek-vista',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/creek-vista.webp',
            },
            {
                id: 'creek',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/creek.webp',
            },
            {
                id: 'dnr-canyon-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/dnr-canyon-view.webp',
            },
            {
                id: 'endor-view',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/endor-view.webp',
            },
            {
                id: 'endor-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/endor-walk.webp',
            },
            {
                id: 'glacier',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/glacier.webp',
            },
            {
                id: 'glacier2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/glacier2.webp',
            },
            {
                id: 'valley-view',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/valley-view.webp',
            },
            {
                id: 'valley-view2',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/valley-view2.webp',
            },
            {
                id: 'valley-walk',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/teton/cascade-creek/valley-walk.webp',
            },
        ],
    },
    '2023/wyoming/random': {
        panos: [],
        images: [
            {
                id: 'battle-of-pierres-hole',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/battle-of-pierres-hole.webp',
            },
            {
                id: 'earned-it',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/earned-it.webp',
            },
            {
                id: 'kampai-drinks',
                width: 1316,
                height: 1755,
                src: 'https://clemann.app/2023/wyoming/random/kampai-drinks.webp',
            },
            {
                id: 'kampai-selfie',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/kampai-selfie.webp',
            },
            {
                id: 'kampai-sushi',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/kampai-sushi.webp',
            },
            {
                id: 'old-faithful-ipa',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/old-faithful-ipa.webp',
            },
            {
                id: 'ron-smokey',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/ron-smokey.webp',
            },
            {
                id: 'stars',
                width: 2016,
                height: 1512,
                src: 'https://clemann.app/2023/wyoming/random/stars.webp',
            },
            {
                id: 'tips-up',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/tips-up.webp',
            },
            {
                id: 'yellowstone-whiskey',
                width: 1512,
                height: 2016,
                src: 'https://clemann.app/2023/wyoming/random/yellowstone-whiskey.webp',
            },
        ],
    },
};
